Getting data from the wiki page given

In [14]:
import pandas as pd

In [30]:
#specify the url
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

In [31]:
tables = pd.read_html(url)

Creating dataframe from the wiki data

In [32]:
tables[0].head()

          0             1                 2
0  Postcode       Borough     Neighbourhood
1       M1A  Not assigned      Not assigned
2       M2A  Not assigned      Not assigned
3       M3A    North York         Parkwoods
4       M4A    North York  Victoria Village

In [33]:
df = tables[0]
df.head(10)

          0                 1                 2
0  Postcode           Borough     Neighbourhood
1       M1A      Not assigned      Not assigned
2       M2A      Not assigned      Not assigned
3       M3A        North York         Parkwoods
4       M4A        North York  Victoria Village
5       M5A  Downtown Toronto      Harbourfront
6       M5A  Downtown Toronto       Regent Park
7       M6A        North York  Lawrence Heights
8       M6A        North York    Lawrence Manor
9       M7A      Queen's Park      Not assigned

In [34]:
df.columns

Int64Index([0, 1, 2], dtype='int64')

Giving appropriate columns

In [35]:
df.columns = df.iloc[0]

In [36]:
df.reindex(df.index.drop(0))

,Postcode,Borough,Neighbourhood
1,M1A,Not assigned,Not assigned
2,M2A,Not assigned,Not assigned
3,M3A,North York,Parkwoods
4,M4A,North York,Victoria Village
5,M5A,Downtown Toronto,Harbourfront
6,M5A,Downtown Toronto,Regent Park
7,M6A,North York,Lawrence Heights
8,M6A,North York,Lawrence Manor
9,M7A,Queen's Park,Not assigned
10,M8A,Not assigned,Not assigned
11,M9A,Etobicoke,Islington Avenue
12,M1B,Scarborough,Rouge
13,M1B,Scarborough,Malvern
14,M2B,Not assigned,Not assigned
15,M3B,North York,Don Mills North
16,M4B,East York,Woodbine Gardens
17,M4B,East York,Parkview Hill
18,M5B,Downtown Toronto,Ryerson
19,M5B,Downtown Toronto,Garden District
20,M6B,North York,Glencairn
21,M7B,Not assigned,Not assigned
22,M8B,Not assigned,Not assigned
23,M9B,Etobicoke,Cloverdale
24,M9B,Etobicoke,Islington
25,M9B,Etobicoke,Martin Grove
26,M9B,Etobicoke,Princess Gardens
27,M9B,Etobicoke,West Deane Park
28,M1C,Scarborough,Highland Creek
29,M1C,Scarborough,Rouge Hill
30,M1C,Scarborough,Port Union
...,...,...,...
259,M9X,Not assigned,Not assigned
260,M1Y,Not assigned,Not assigned
261,M2Y,Not assigned,Not assigned
262,M3Y,Not assigned,Not assigned
263,M4Y,Downtown Toronto,Church and Wellesley
264,M5Y,Not assigned,Not assigned
265,M6Y,Not assigned,Not assigned
266,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
267,M8Y,Etobicoke,Humber Bay
268,M8Y,Etobicoke,King's Mill Park
269,M8Y,Etobicoke,Kingsway Park South East
270,M8Y,Etobicoke,Mimico NE
271,M8Y,Etobicoke,Old Mill South
272,M8Y,Etobicoke,The Queensway East
273,M8Y,Etobicoke,Royal York South East
274,M8Y,Etobicoke,Sunnylea
275,M9Y,Not assigned,Not assigned
276,M1Z,Not assigned,Not assigned
277,M2Z,Not assigned,Not assigned
278,M3Z,Not assigned,Not assigned
279,M4Z,Not assigned,Not assigned
280,M5Z,Not assigned,Not assigned
281,M6Z,Not assigned,Not assigned
282,M7Z,Not assigned,Not assigned
283,M8Z,Etobicoke,Kingsway Park South West
284,M8Z,Etobicoke,Mimico NW
285,M8Z,Etobicoke,The Queensway West
286,M8Z,Etobicoke,Royal York South West
287,M8Z,Etobicoke,South of Bloor
288,M9Z,Not assigned,Not assigned

In [38]:
df.describe()

0      Postcode       Borough Neighbourhood
count       289           289           289
unique      181            13           210
top         M9V  Not assigned  Not assigned
freq          8            77            78

Selecting the data not having Not assigned in Borough column

In [39]:
df=df[df.Borough != 'Not assigned']

In [40]:
df.describe()

0      Postcode    Borough Neighbourhood
count       212        212           212
unique      104         12           210
top         M9V  Etobicoke     Runnymede
freq          8         45             2

In [41]:
df.shape

(212, 3)

Replace value of Borough to Neighbourhood where it is "Not assigned"

In [42]:
df['Neighbourhood']=df['Neighbourhood'].replace('Not assigned', df['Borough'])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [43]:
df.head(10)

0   Postcode           Borough     Neighbourhood
0   Postcode           Borough     Neighbourhood
3        M3A        North York         Parkwoods
4        M4A        North York  Victoria Village
5        M5A  Downtown Toronto      Harbourfront
6        M5A  Downtown Toronto       Regent Park
7        M6A        North York  Lawrence Heights
8        M6A        North York    Lawrence Manor
9        M7A      Queen's Park      Queen's Park
11       M9A         Etobicoke  Islington Avenue
12       M1B       Scarborough             Rouge

In [44]:
df.shape

(212, 3)